---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: productsapideployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: products
 template:
  metadata:
   name: products
   labels:
     app: products
  spec:
    containers:
    - name: productscontainer
      image: sagard1531/products
      ports:
      - containerPort: 8080
      env:
      # From ConfigMap
      - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        valueFrom:
          configMapKeyRef:
            name: products-config
            key: spring.datasource.driver-class-name

      - name: SPRING_DATASOURCE_URL
        valueFrom:
          configMapKeyRef:
            name: products-config
            key: spring.datasource.url

      # From Secret
      - name: SPRING_DATASOURCE_USERNAME
        valueFrom:
          secretKeyRef:
            name: products-secret
            key: spring.datasource.username
      
      - name: SPRING_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: products-secret
            key: spring.datasource.password
              
---
apiVersion: v1
kind: Service
metadata:
 name: productssvc
spec:
  type: LoadBalancer
  selector:
   app: products
  ports:
   - port: 80
     targetPort: 8080
...
